add: no scan

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -24,84 +24,84 @@ env:
   SONAR_SKIP: ""
 
 jobs:
-  sonarqube-scan:
-    name: SonarQube Analysis
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 # Required for SonarQube blame info
+  # sonarqube-scan:
+  #   name: SonarQube Analysis
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0 # Required for SonarQube blame info
 
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: "20"
-          cache: "npm"
+  #     - name: Setup Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: "20"
+  #         cache: "npm"
 
-      - name: Install dependencies
-        run: npm i
+  #     - name: Install dependencies
+  #       run: npm i
 
-      - name: Run tests with coverage (if it exists)
-        run: |
-          if npm run | grep -q ' test'; then
-            npm test -- --coverage --watchAll=false
-          else
-            echo "No test script found, skipping tests."
-          fi
+  #     - name: Run tests with coverage (if it exists)
+  #       run: |
+  #         if npm run | grep -q ' test'; then
+  #           npm test -- --coverage --watchAll=false
+  #         else
+  #           echo "No test script found, skipping tests."
+  #         fi
 
-      - name: Check SonarQube Secrets
-        run: |
-          if [ -z "${{ secrets.SONAR_TOKEN }}" ] || [ -z "${{ secrets.SONAR_HOST_URL }}" ]; then
-            echo "SONAR_TOKEN or SONAR_HOST_URL is missing in GitHub Secrets."
-            echo "Skipping SonarQube scan..."
-            echo "SONAR_SKIP=true" >> $GITHUB_ENV
-          else
-            echo "SONAR_SKIP=false" >> $GITHUB_ENV
-          fi
+  #     - name: Check SonarQube Secrets
+  #       run: |
+  #         if [ -z "${{ secrets.SONAR_TOKEN }}" ] || [ -z "${{ secrets.SONAR_HOST_URL }}" ]; then
+  #           echo "SONAR_TOKEN or SONAR_HOST_URL is missing in GitHub Secrets."
+  #           echo "Skipping SonarQube scan..."
+  #           echo "SONAR_SKIP=true" >> $GITHUB_ENV
+  #         else
+  #           echo "SONAR_SKIP=false" >> $GITHUB_ENV
+  #         fi
 
-      - name: SonarQube Scan
-        if: env.SONAR_SKIP == 'false'
-        uses: SonarSource/sonarqube-scan-action@v5
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_HOST_URL: https://sonarcloud.io
-        with:
-          args: >
-            -Dsonar.organization=tochratana
-            -Dsonar.projectKey=template-nextjs
-            -Dsonar.sources=src
+  #     - name: SonarQube Scan
+  #       if: env.SONAR_SKIP == 'false'
+  #       uses: SonarSource/sonarqube-scan-action@v5
+  #       env:
+  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #         SONAR_HOST_URL: https://sonarcloud.io
+  #       with:
+  #         args: >
+  #           -Dsonar.organization=tochratana
+  #           -Dsonar.projectKey=template-nextjs
+  #           -Dsonar.sources=src
 
-  trivy-fs-scan:
-    name: Trivy Filesystem Scan
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # trivy-fs-scan:
+  #   name: Trivy Filesystem Scan
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-      - name: Run Trivy on filesystem
-        uses: aquasecurity/trivy-action@master
-        with:
-          scan-type: "fs"
-          scan-ref: "."
-          format: "sarif"
-          output: "trivy-fs-results.sarif"
-          severity: "CRITICAL,HIGH"
-          exit-code: "1"
-          ignore-unfixed: true
+  #     - name: Run Trivy on filesystem
+  #       uses: aquasecurity/trivy-action@master
+  #       with:
+  #         scan-type: "fs"
+  #         scan-ref: "."
+  #         format: "sarif"
+  #         output: "trivy-fs-results.sarif"
+  #         severity: "CRITICAL,HIGH"
+  #         exit-code: "1"
+  #         ignore-unfixed: true
 
-      - name: Upload Trivy FS results to GitHub Security
-        uses: github/codeql-action/upload-sarif@v4
-        # Use success() || failure() instead of always() to avoid triggering if checkout fails
-        if: success() || failure()
-        with:
-          sarif_file: "trivy-fs-results.sarif"
-          category: "trivy-filesystem"
+  #     - name: Upload Trivy FS results to GitHub Security
+  #       uses: github/codeql-action/upload-sarif@v4
+  #       # Use success() || failure() instead of always() to avoid triggering if checkout fails
+  #       if: success() || failure()
+  #       with:
+  #         sarif_file: "trivy-fs-results.sarif"
+  #         category: "trivy-filesystem"
 
   build-scan-push:
     name: Build, Scan & Push Image
     runs-on: ubuntu-latest
-    needs: [sonarqube-scan, trivy-fs-scan]
+    # needs: [sonarqube-scan, trivy-fs-scan]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
